/*
    WE
    DO
    NOT
    TALK
    ABOUT
    THIS
*/

mergeInto(LibraryManager.library, {
    audio_init: function(...args) { return audio_init(...args) },

    console_debug: function(...args) { return importObject.env.console_debug(...args); },
    console_log: function(...args) { return importObject.env.console_log(...args); },
    console_info: function(...args) { return importObject.env.console_info(...args); },
    console_warn: function(...args) { return importObject.env.console_warn(...args); },
    console_error: function(...args) { return importObject.env.console_error(...args); },
    set_emscripten_shader_hack: function(...args) { return importObject.env.set_emscripten_shader_hack(...args); },
    sapp_set_clipboard: function(...args) { return importObject.env.sapp_set_clipboard(...args); },
    dpi_scale: function (...args) { return importObject.env.dpi_scale(...args); },
    rand: function(...args) { return importObject.env.rand(...args); },
    now: function(...args) { return importObject.env.now(...args); },
    canvas_width: function(...args) { return importObject.env.canvas_width(...args); },
    canvas_height: function(...args) { return importObject.env.canvas_height(...args); },
    glClearDepthf: function(...args) { return importObject.env.glClearDepthf(...args); },
    glClearColor: function(...args) { return importObject.env.glClearColor(...args); },
    glClearStencil: function(...args) { return importObject.env.glClearStencil(...args); },
    glColorMask: function(...args) { return importObject.env.glColorMask(...args); },
    glScissor: function(...args) { return importObject.env.glScissor(...args); },
    glClear: function(...args) { return importObject.env.glClear(...args); },
    glGenTextures: function(...args) { return importObject.env.glGenTextures(...args); },
    glActiveTexture: function(...args) { return importObject.env.glActiveTexture(...args); },
    glBindTexture: function(...args) { return importObject.env.glBindTexture(...args); },
    glTexImage2D: function(...args) { return importObject.env.glTexImage2D(...args); },
    glTexSubImage2D: function(...args) { return importObject.env.glTexSubImage2D(...args); },
    glReadPixels: function(...args) { return importObject.env.glReadPixels(...args); },
    glTexParameteri: function(...args) { return importObject.env.glTexParameteri(...args); },
    glUniform1fv: function(...args) { return importObject.env.glUniform1fv(...args); },
    glUniform2fv: function(...args) { return importObject.env.glUniform2fv(...args); },
    glUniform3fv: function(...args) { return importObject.env.glUniform3fv(...args); },
    glUniform4fv: function(...args) { return importObject.env.glUniform4fv(...args); },
    glUniform1iv: function(...args) { return importObject.env.glUniform1iv(...args); },
    glUniform2iv: function(...args) { return importObject.env.glUniform2iv(...args); },
    glUniform3iv: function(...args) { return importObject.env.glUniform3iv(...args); },
    glUniform4iv: function(...args) { return importObject.env.glUniform4iv(...args); },
    glBlendFunc: function(...args) { return importObject.env.glBlendFunc(...args); },
    glBlendEquationSeparate: function(...args) { return importObject.env.glBlendEquationSeparate(...args); },
    glDisable: function(...args) { return importObject.env.glDisable(...args); },
    glDrawElements: function(...args) { return importObject.env.glDrawElements(...args); },
    glGetIntegerv: function(...args) {
        // THIS IS A SUPER UNSTABLE HACK!
        // MQ needs access to these, but i don't know how to execute code between emscripten & MQ.
        // this appears to be the first function that's called.
        // yes, really.
        wasm_memory = wasmMemory;
        wasm_exports = Module.asm;
        return importObject.env.glGetIntegerv(...args);
    },
    glUniform1f: function(...args) { return importObject.env.glUniform1f(...args); },
    glUniform1i: function(...args) { return importObject.env.glUniform1i(...args); },
    glGetAttribLocation: function(...args) { return importObject.env.glGetAttribLocation(...args); },
    glEnableVertexAttribArray: function(...args) { return importObject.env.glEnableVertexAttribArray(...args); },
    glDisableVertexAttribArray: function(...args) { return importObject.env.glDisableVertexAttribArray(...args); },
    glVertexAttribPointer: function(...args) { return importObject.env.glVertexAttribPointer(...args); },
    glGetUniformLocation: function(...args) { return importObject.env.glGetUniformLocation(...args); },
    glUniformMatrix4fv: function(...args) { return importObject.env.glUniformMatrix4fv(...args); },
    glUseProgram: function(...args) { return importObject.env.glUseProgram(...args); },
    glGenVertexArrays: function(...args) { return importObject.env.glGenVertexArrays(...args); },
    glGenFramebuffers: function(...args) { return importObject.env.glGenFramebuffers(...args); },
    glBindVertexArray: function(...args) { return importObject.env.glBindVertexArray(...args); },
    glBindFramebuffer: function(...args) { return importObject.env.glBindFramebuffer(...args); },
    glGenBuffers: function(...args) { return importObject.env.glGenBuffers(...args); },
    glBindBuffer: function(...args) { return importObject.env.glBindBuffer(...args); },
    glBufferData: function(...args) { return importObject.env.glBufferData(...args); },
    glBufferSubData: function(...args) { return importObject.env.glBufferSubData(...args); },
    glEnable: function(...args) { return importObject.env.glEnable(...args); },
    glFlush: function(...args) { return importObject.env.glFlush(...args); },
    glFinish: function(...args) { return importObject.env.glFinish(...args); },
    glDepthFunc: function(...args) { return importObject.env.glDepthFunc(...args); },
    glBlendFuncSeparate: function(...args) { return importObject.env.glBlendFuncSeparate(...args); },
    glViewport: function(...args) { return importObject.env.glViewport(...args); },
    glDrawArrays: function(...args) { return importObject.env.glDrawArrays(...args); },
    glCreateProgram: function(...args) { return importObject.env.glCreateProgram(...args); },
    glAttachShader: function(...args) { return importObject.env.glAttachShader(...args); },
    glLinkProgram: function(...args) { return importObject.env.glLinkProgram(...args); },
    glPixelStorei: function(...args) { return importObject.env.glPixelStorei(...args); },
    glFramebufferTexture2D: function(...args) { return importObject.env.glFramebufferTexture2D(...args); },
    glGetProgramiv: function(...args) { return importObject.env.glGetProgramiv(...args); },
    glCreateShader: function(...args) { return importObject.env.glCreateShader(...args); },
    glStencilFuncSeparate: function(...args) { return importObject.env.glStencilFuncSeparate(...args); },
    glStencilMaskSeparate: function(...args) { return importObject.env.glStencilMaskSeparate(...args); },
    glStencilOpSeparate: function(...args) { return importObject.env.glStencilOpSeparate(...args); },
    glFrontFace: function(...args) { return importObject.env.glFrontFace(...args); },
    glCullFace: function(...args) { return importObject.env.glCullFace(...args); },
    glCopyTexImage2D: function(...args) { return importObject.env.glCopyTexImage2D(...args); },
    glShaderSource: function(...args) { return importObject.env.glShaderSource(...args); },
    glGetProgramInfoLog: function(...args) { return importObject.env.glGetProgramInfoLog(...args); },
    glCompileShader: function(...args) { return importObject.env.glCompileShader(...args); },
    glGetShaderiv: function(...args) { return importObject.env.glGetShaderiv(...args); },
    glGetShaderInfoLog: function(...args) { return importObject.env.glGetShaderInfoLog(...args); },
    glVertexAttribDivisor: function(...args) { return importObject.env.glVertexAttribDivisor(...args); },
    glDrawArraysInstanced: function(...args) { return importObject.env.glDrawArraysInstanced(...args); },
    glDrawElementsInstanced: function(...args) { return importObject.env.glDrawElementsInstanced(...args); },
    glDeleteShader: function(...args) { return importObject.env.glDeleteShader(...args); },
    glDeleteBuffers: function(...args) { return importObject.env.glDeleteBuffers(...args); },
    glDeleteFramebuffers: function(...args) { return importObject.env.glDeleteFramebuffers(...args); },
    glDeleteTextures: function(...args) { return importObject.env.glDeleteTextures(...args); },
    glGenQueries: function(...args) { return importObject.env.glGenQueries(...args); },
    glDeleteQueries: function(...args) { return importObject.env.glDeleteQueries(...args); },
    glBeginQuery: function(...args) { return importObject.env.glBeginQuery(...args); },
    glEndQuery: function(...args) { return importObject.env.glEndQuery(...args); },
    glGetQueryObjectiv: function(...args) { return importObject.env.glGetQueryObjectiv(...args); },
    glGetQueryObjectui64v: function(...args) { return importObject.env.glGetQueryObjectui64v(...args); },
    setup_canvas_size: function(...args) { return importObject.env.setup_canvas_size(...args); },
    run_animation_loop: function(...args) { return importObject.env.run_animation_loop(...args); },
    fs_load_file: function(...args) { return importObject.env.fs_load_file(...args); },
    fs_get_buffer_size: function(...args) { return importObject.env.fs_get_buffer_size(...args); },
    fs_take_buffer: function(...args) { return importObject.env.fs_take_buffer(...args); },
    sapp_set_cursor_grab: function(...args) { return importObject.env.sapp_set_cursor_grab(...args); },
    sapp_set_cursor: function(...args) { return importObject.env.sapp_set_cursor(...args); },
    sapp_is_fullscreen: function(...args) { return importObject.env.sapp_is_fullscreen(...args); },
    sapp_set_fullscreen: function(...args) { return importObject.env.sapp_set_fullscreen(...args); },
    sapp_set_window_size: function(...args) { return importObject.env.sapp_set_window_size(...args); },
});
